### ISSUE TITLE
repository not found error

### ISSUE THREAD

**Issue by Dylan-Prins** [SimonTheLeg/semver-tag-from-pr-action#36]
Hi,

i can't find out what i am doing wrong:

![image](https://user-images.githubusercontent.com/8777848/230722179-3e9d6caf-ee9c-4ddd-a78d-96e9d79cf07b.png)

``` yaml
name: tag

on:
  push:
    branches: ['main']

permissions:
  contents: write
  pull-requests: read

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: bump semVer
        uses: simontheleg/semver-tag-from-pr-action@v1.4.0
        id: bump-semver
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          repo_ssh_key: ${{ secrets.SEMVER_TAG_SSH_KEY}}
          label_major: major
          label_minor: minor
          label_patch: patch
          label_none: no-release
          should_set_tag: true
          should_push_tag: true
```

**Comment by SimonTheLeg** [comment]
Hi @Dylan-Prins, I think the issue is, that you need to clone the repository first. For this, I would recommend using the `actions/checkout@v3` action from Github. You can put this step before your `bump semVer` step:

```
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # we need full git-history to determine the last semVer tag
          ssh-key: ${{ secrets.SEMVER_TAG_SSH_KEY}} # insert the name you gave the GH secret
```
