### ISSUE TITLE
ssh: no key found

### ISSUE THREAD

**Issue by sosafe-stephan-bothur** [SimonTheLeg/semver-tag-from-pr-action#38]
Hi! 👋

This might be related to https://github.com/SimonTheLeg/semver-tag-from-pr-action/issues/37.

For the simple example workflow:

```yml
on:
  push:
    branches:
      - main # can be main or any other release branch
jobs:
  semver_tag_from_pr:
    # permissions required to find PR for last commit and push the new tag
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # we need full git-history to determine the last semVer tag
      - name: bump semVer
        uses: simontheleg/semver-tag-from-pr-action@v1.4.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          should_set_tag: false
          should_push_tag: false
```

I'm running into `ssh: no key found`:

```bash
Run simontheleg/semver-tag-from-pr-action@v1.4.0
  with:
    repo_token: ***
    should_set_tag: false
    should_push_tag: false
    trunk: main
    label_major: merge-major
    label_minor: merge-minor
    label_patch: merge-patch
    label_none: merge-none
Run mkdir -p /home/runner/work/_temp/_github_home && \
  mkdir -p /home/runner/work/_temp/_github_home && \
  ssh-keyscan -t ecdsa github.com > /home/runner/work/_temp/_github_home/known_hosts && \
  export SSH_KNOWN_HOSTS="/github/home/known_hosts" && \
  export INPUT_REPO_SSH_KEY=$(echo "$INPUT_REPO_SSH_KEY" | base64 -w 0) && \
  docker run \
  --workdir /github/workspace \
  -v "${WORKSPACE}":"${WORKSPACE}" \
  -v "/var/run/docker.sock":"/var/run/docker.sock" \
  -v "/home/runner/work/_temp/_github_home":"/github/home" \
  -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" \
  -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" \
  --env-file <(env) \
  ghcr.io/simontheleg/semver-tag-from-pr-action:${VERSION}
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    VERSION: v1.4.0
    WORKSPACE: /home/runner/work/test/test
    INPUT_TRUNK: main
    INPUT_LABEL_MAJOR: merge-major
    INPUT_LABEL_MINOR: merge-minor
    INPUT_LABEL_PATCH: merge-patch
    INPUT_LABEL_NONE: merge-none
    INPUT_REPO_TOKEN: ***
    INPUT_REPO_SSH_KEY: 
    INPUT_REPO_STORAGE_PATH_OVERWRITE: 
    INPUT_SHOULD_SET_TAG: false
    INPUT_SHOULD_PUSH_TAG: false
# github.com:22 SSH-2.0-babeld-fc59fe75
Unable to find image 'ghcr.io/simontheleg/semver-tag-from-pr-action:v1.4.0' locally
v1.4.0: Pulling from simontheleg/semver-tag-from-pr-action
686d381e6088: Pulling fs layer
64846363f160: Pulling fs layer
686d381e6088: Download complete
64846363f160: Verifying Checksum
64846363f160: Download complete
686d381e6088: Pull complete
64846363f160: Pull complete
Digest: sha2[5]: eb60ba28077d8a386b150f6f84bfbc0dc937f120878e3f7c6f31fdb068c67c1a
Status: Downloaded newer image for ghcr.io/simontheleg/semver-tag-from-pr-action:v1.4.0
ssh: no key found
```
